// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaProject.Context;

namespace PizzaProject.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaProject.Context.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Anchovies");

                    b.Property<double>("Bacon");

                    b.Property<double>("Basil");

                    b.Property<double>("Beef");

                    b.Property<double>("Cheese");

                    b.Property<double>("Chicken");

                    b.Property<double>("Dough");

                    b.Property<double>("Feta");

                    b.Property<double>("Garlic");

                    b.Property<double>("GreenPeppers");

                    b.Property<double>("Ham");

                    b.Property<int>("LocationId");

                    b.Property<double>("Mushrooms");

                    b.Property<double>("Olives");

                    b.Property<double>("Onions");

                    b.Property<double>("Parmesan");

                    b.Property<double>("Pepperoni");

                    b.Property<double>("Pineapple");

                    b.Property<double>("RedPeppers");

                    b.Property<double>("Ricotta");

                    b.Property<double>("Sausage");

                    b.Property<double>("Spinach");

                    b.Property<double>("TomatoSauce");

                    b.Property<double>("Tomatoes");

                    b.Property<double>("WhiteSauce");

                    b.HasKey("Id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("PizzaProject.Context.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InventoryId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("PizzaProject.Context.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocationId");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PizzaProject.Context.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cheese");

                    b.Property<string>("Crust");

                    b.Property<decimal>("Price");

                    b.Property<string>("Sauce");

                    b.Property<string>("Topping1");

                    b.Property<string>("Topping2");

                    b.Property<string>("Topping3");

                    b.Property<string>("Topping4");

                    b.Property<string>("Topping5");

                    b.Property<string>("Topping6");

                    b.HasKey("Id");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("PizzaProject.Context.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
